In [1]:
!nvidia-smi


Wed Nov  1 17:49:04 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   52C    P8    11W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [2]:
import os
HOME = os.getcwd()
print(HOME)

/content


In [3]:
!pip install ultralytics

from IPython.display import Image

import ultralytics


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 644.8/644.8 kB 5.9 MB/s eta 0:00:00


In [ ]:
import random
import shutil
import tensorflow as tf
from sklearn.metrics import confusion_matrix, accuracy_score


In [ ]:
!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="Yp3RK5raZJ7EW8cRulik")
project = rf.workspace("new-workspace-onq0e").project("covid-x-ray-images")
dataset = project.version(1).download("folder")


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.8/58.8 kB 1.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 155.3/155.3 kB 9.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 178.7/178.7 kB 17.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.8/58.8 kB 9.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.1/49.1 MB 10.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.8/67.8 kB 8.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.2/72.2 kB 11.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.5/54.5 kB 8.2 MB/s eta 0:00:00
  Attempting uninstall: pyparsing
    Found existing installation: pyparsing 3.1.1
    Uninstalling pyparsing-3.1.1:
      Successfully uninstalled pyparsing-3.1.1
  Attempting uninstall: opencv-python-headless
    Found existing installation: opencv-python-headless 4.8.1.78
    Uninstalling opencv-python-headless-4.8.1.78:
      Successfully uninstal

In [5]:
rf = Roboflow(api_key="Yp3RK5raZJ7EW8cRulik")
project = rf.workspace("joseph-nelson").project("covid-19-and-pneumonia-scans")
dataset = project.version(1).download("folder")

loading Roboflow workspace...
loading Roboflow project...



Extracting Dataset Version Zip to COVID-19-and-Pneumonia-Scans-1 in folder:: 100%|██████████| 5889/5889 [00:00<00:00, 7396.05it/s]


In [6]:
rf = Roboflow(api_key="Yp3RK5raZJ7EW8cRulik")
project = rf.workspace("umar-farooq").project("classification-kdgyu")
dataset = project.version(1).download("folder")

loading Roboflow workspace...
loading Roboflow project...


Extracting Dataset Version Zip to classification-1 in folder:: 100%|██████████| 12781/12781 [00:01<00:00, 7867.72it/s]


In [7]:

# Define your source and destination directories
source_directories = [
    "/content/COVID-19-and-Pneumonia-Scans-1/train/covid-19",
    "/content/Covid-X-ray-Images-1/test/COVID",
    "/content/Covid-X-ray-Images-1/train/COVID",
    "/content/classification-1/train/COVID-19"
]

destination_directory = "/content/combined_covid-19"

# Create the destination directory if it doesn't exist
if not os.path.exists(destination_directory):
    os.makedirs(destination_directory)

# Loop through source directories and copy their contents to the destination directory
for source_dir in source_directories:
    for filename in os.listdir(source_dir):
        source_path = os.path.join(source_dir, filename)
        destination_path = os.path.join(destination_directory, filename)
        shutil.copy(source_path, destination_path)

# Optionally, you can print the number of files copied
file_count = len(os.listdir(destination_directory))
print(f"Combined {file_count} files into {destination_directory}")


Combined 8326 files into /content/combined_covid-19


In [8]:
# Define your source directories
source_directories = [
    "/content/COVID-19-and-Pneumonia-Scans-1/train/healthy",
    "/content/classification-1/train/Normal",
    "/content/Covid-X-ray-Images-1/test/Normal",
    "/content/Covid-X-ray-Images-1/train/Normal"
]

destination_directory = "/content/combined_data_normal"

# Create the destination directory if it doesn't exist
if not os.path.exists(destination_directory):
    os.makedirs(destination_directory)

# Loop through source directories and copy their contents to the destination directory
for source_dir in source_directories:
    for filename in os.listdir(source_dir):
        source_path = os.path.join(source_dir, filename)
        destination_path = os.path.join(destination_directory, filename)
        shutil.copy(source_path, destination_path)

# Optionally, you can print the number of files copied
file_count = len(os.listdir(destination_directory))
print(f"Combined {file_count} files into {destination_directory}")


Combined 16008 files into /content/combined_data_normal


In [9]:
# Define your source directories
source_directories = [
    "/content/COVID-19-and-Pneumonia-Scans-1/train/pneumonia",
    "/content/Covid-X-ray-Images-1/train/Viral_Pneumonia",
    "/content/Covid-X-ray-Images-1/test/Viral_Pneumonia"
]

destination_directory = "/content/combined_data_pneumonia"

# Create the destination directory if it doesn't exist
if not os.path.exists(destination_directory):
    os.makedirs(destination_directory)

# Loop through source directories and copy their contents to the destination directory
for source_dir in source_directories:
    for filename in os.listdir(source_dir):
        source_path = os.path.join(source_dir, filename)
        destination_path = os.path.join(destination_directory, filename)
        shutil.copy(source_path, destination_path)

# Optionally, you can print the number of files copied
file_count = len(os.listdir(destination_directory))
print(f"Combined {file_count} files into {destination_directory}")


Combined 5061 files into /content/combined_data_pneumonia


In [15]:
# Directory paths
combined_covid19_directory = "/content/combined_covid-19"
combined_data_normal_directory = "/content/combined_data_normal"
combined_data_pneumonia_directory = "/content/combined_data_pneumonia"
destination_directory = "/content/data"

# Create the main "data" directory if it doesn't exist
if not os.path.exists(destination_directory):
    os.makedirs(destination_directory)

# Function to copy a random set of files from a source directory to the destination
def copy_random_files(source_directory, destination_subdirectory, num_files):
    subdirectory_path = os.path.join(destination_directory, destination_subdirectory)
    if not os.path.exists(subdirectory_path):
        os.makedirs(subdirectory_path)

    filenames = os.listdir(source_directory)
    random_files = random.sample(filenames, num_files)
    for filename in random_files:
        source_path = os.path.join(source_directory, filename)
        destination_path = os.path.join(subdirectory_path, filename)
        shutil.copy(source_path, destination_path)

# Copy 5,000 random files from each combined directory to their respective subfolders within the "data" directory
copy_random_files(combined_covid19_directory, "covid19", 5000)
copy_random_files(combined_data_normal_directory, "normal", 5000)
copy_random_files(combined_data_pneumonia_directory, "pneumonia", 5000)

# Optionally, you can print a message indicating the operation was successful
print("Successfully copied 5,000 random files into subfolders in the 'data' directory.")


Successfully copied 5,000 random files into subfolders in the 'data' directory.


In [16]:
pip install split-folders

In [18]:
import splitfolders

#Split data to (Train,val,test)
splitfolders = splitfolders.ratio('/content/data', output="/content/data_split", seed=42, ratio=(.7, .2, .1),group_prefix=None) # default values

Copying files: 15000 files [00:02, 6393.19 files/s]


In [19]:
!pip install tensorflow


In [27]:
from ultralytics import YOLO

# Load a model
model = YOLO("yolov8m-cls.pt")  # load a pretained model

results = model.train(
    data='/content/data_split',
    epochs=20,
    imgsz=256, # Specify 'adam' optimize  # Specify a custom learning rate
    augment=True
)

100%|██████████| 32.7M/32.7M [00:00<00:00, 203MB/s]
Ultralytics YOLOv8.0.203 🚀 Python-3.10.12 torch-2.1.0+cu118 CUDA:0 (Tesla T4, 15102MiB)
engine/trainer: task=classify, mode=train, model=yolov8m-cls.pt, data=/content/data_split, epochs=20, patience=50, batch=16, imgsz=256, save=True, save_period=-1, cache=False, device=None, workers=8, project=None, name=train6, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, vid_stride=1, stream_buffer=False, line_width=None, visualize=False, augment=True, agnostic_nms=False, classes=None, retina_masks=False

In [68]:
# Load your YOLO model
model = YOLO("/content/runs/classify/train6/weights/best.pt")  # Load your pretrained model

# Define class labels for your categories
class_labels = {
    0: 'covid19',
    1: 'normal',
    2: 'pneumonia'
}

# Directory paths for the test images
test_dirs = [
    "/content/data_split/test/covid19",
    "/content/data_split/test/normal",
    "/content/data_split/test/pneumonia"
]

true_labels = []
predicted_labels = []

for class_idx, test_dir in enumerate(test_dirs):
    class_label = class_labels[class_idx]

    # Get a list of image file paths in the directory
    image_files = [os.path.join(test_dir, file) for file in os.listdir(test_dir) if file.endswith(".jpg")]

    for image_file in image_files:
        results = model.predict(image_file)
        result_list = []

        for r in results:
            names_dict = r.names
            probs = r.probs.data.tolist()
            predicted_class = np.argmax(probs)
            result_list.append(predicted_class)

        true_labels.append(class_idx)
        predicted_labels.append(max(set(result_list), key=result_list.count))


image 1/1 /content/data_split/test/covid19/COVID-924_png.rf.551823eb7a4f12b2c2c97aefa65f471a.jpg: 256x256 covid19 1.00, normal 0.00, pneumonia 0.00, 8.2ms
Speed: 1.4ms preprocess, 8.2ms inference, 0.1ms postprocess per image at shape (1, 3, 256, 256)

image 1/1 /content/data_split/test/covid19/covid_796_png.rf.68519ba19244da54df2f51bf39003cd1.jpg: 256x256 covid19 1.00, normal 0.00, pneumonia 0.00, 7.5ms
Speed: 1.5ms preprocess, 7.5ms inference, 0.1ms postprocess per image at shape (1, 3, 256, 256)

image 1/1 /content/data_split/test/covid19/COVID-867_png.rf.bd2e723cb2c4eb36ecb077810e50ddda.jpg: 256x256 covid19 1.00, pneumonia 0.00, normal 0.00, 7.4ms
Speed: 1.3ms preprocess, 7.4ms inference, 0.1ms postprocess per image at shape (1, 3, 256, 256)

image 1/1 /content/data_split/test/covid19/covid_3277_png.rf.f656ec0b059298104f86d8e06d253367.jpg: 256x256 covid19 0.95, normal 0.05, pneumonia 0.00, 7.3ms
Speed: 1.5ms preprocess, 7.3ms inference, 0.1ms postprocess per image at shape (1, 3, 2

In [69]:
# Calculate the confusion matrix
confusion = confusion_matrix(true_labels, predicted_labels)

# Calculate accuracy
accuracy = accuracy_score(true_labels, predicted_labels)

print("Confusion Matrix:")
print(confusion)
print("Accuracy:", accuracy)


Confusion Matrix:
[[485  10   5]
 [ 16 464  20]
 [  1  24 475]]
Accuracy: 0.9493333333333334
